[package]
name = "grid_pursuit"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.0"
fixedbitset = "0.4.1"
array-init = "2.0.0"
itertools = "0.10.3"
nalgebra = "0.30.1"
arrayvec = "0.7.2"
anyhow = "1.0.35"
bimap = "0.6.2"
lazycell = "1.3.0"
thiserror = "1.0.30"
